### ISSUE TITLE
Gitlab Migration: Please log into GL with your GH account ASAP

### ISSUE THREAD

**Issue by beenje** [tango-cs/itango#23]
Dear itango participants (via commits, comments on issue or pull requests, issue creator),

If you have contributed in any way (commit, issue or Pull Request creation or comment) to itango, please log into Gitlab.com using your Github account ASAP.
See tango-controls/TangoTickets#47 for details.

Please click on the following link and add your github account name to this framapad when you've already done the login to Gitlab.com using your Github account:
https://mensuel.framapad.org/p/migration_ready_2548763689

For convenience, here is the list of contributors we could already find (and who did not signal they had done it yet for another repo):

- [ ] @vxgmichel
- [ ] @tiagocoutinho
- [ ] @sbodomerle
- [x] @PhilLAL
- [x] @johanfforsberg
- [ ] @rhomspuron
- [ ] @nleclercq

The deadline for the migration is the 19th of January 2021.

**Comment by PhilLAL** [comment]
Hi @beenje
thanks for the message.
How can I do if I already have a gitlab account with another name ?

**Comment by beenje** [comment]
Do you use the same e-mail address?
If not, you should add the e-mail address used on GH to your GL account.
Then:
- make sure your email is public in your GitHub profile
- go to https://gitlab.com/-/profile/account and click on connect to GitHub

**Comment by PhilLAL** [comment]
Ok, solved.
